#服务配置
server:
  port: 9001
#spring配置
spring:
  #1.应用配置
  application:
    name: ihrm-company #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ihrm?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 330124
  redis:
    host: 116.62.26.142
    port: 6379
  #3.JPA
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
######################dubbo##################
# Dubbo Protocol 提供服务的名字和端口

dubbo:
  protocol:
    name: dubbo
    port: 12340
  ## Dubbo Registry 注册中心的地址
  registry:
    address: zookeeper://127.0.0.1:2181
    register: true
#  monitor:
#    address: 127.0.0.1:7002
